Repository hashicorp/terraform-exec, pull requests merged in 2020-09, with the labels that each got.

#77 Add more godoc
  tfexec/apply.go
  tfexec/destroy.go
  tfexec/doc.go
  tfexec/import.go
  tfexec/init.go
  tfexec/options.go
  tfexec/output.go
  tfexec/plan.go
  tfexec/providers_schema.go
  tfexec/refresh.go
  tfexec/terraform.go
  tfinstall/doc.go
Labels: documentation

#76 Set user agent appends for tests
  tfexec/internal/e2etest/util_test.go
  tfexec/internal/testutil/tfcache.go
  tfinstall/download.go
  tfinstall/exact_version.go
  tfinstall/http.go
  tfinstall/latest_version.go
Labels: enhancement, testing

#66 Add well known error for required_version issues
  tfexec/cmd.go
  tfexec/errors.go
  tfexec/internal/e2etest/errors_test.go
  tfexec/internal/e2etest/testdata/tf99/main.tf
Labels: enhancement

#83 Add ShowPlanFileRaw
  tfexec/show.go
  tfexec/show_test.go
Labels: enhancement

#74 add goreleaser config
  .gitignore
  .goreleaser.yml
  scripts/release/release.sh
Labels: tfinstall

#72 Add mac builds, speed up win builds
  .circleci/config.yml
Labels: testing
