Repository hashicorp/terraform-exec, pull requests merged in 2021-11, with the labels that each got.

#245 Add support for the `workspace show` command
  tfexec/internal/e2etest/workspace_test.go
  tfexec/version.go
  tfexec/workspace_show.go
  tfexec/workspace_show_test.go
Labels: enhancement, subcommand

#246 Update CHANGELOG.md for `workspace show` command
  CHANGELOG.md
Labels: documentation, subcommand

#252 circleci: bump timeout for E2E tests
  .circleci/config.yml
Labels: ci
