Repository hashicorp/terraform-exec, pull requests merged in 2022-05, with the labels that each got.

#291 tfexec: Add (Terraform).SetLog() method
  tfexec/cmd.go
  tfexec/terraform.go
  tfexec/terraform_test.go
Labels: enhancement

#304 make tests pass (or skip) on darwin/arm64
  tfexec/destroy_test.go
  tfexec/fmt_test.go
  tfexec/get_test.go
  tfexec/graph_test.go
  tfexec/import_test.go
  tfexec/init_test.go
  tfexec/internal/e2etest/testdata/bigint/main.tf
  tfexec/internal/e2etest/util_test.go
  tfexec/output_test.go
  tfexec/providers_lock_test.go
  tfexec/providers_schema_test.go
  tfexec/refresh_test.go
  tfexec/show_test.go
  tfexec/state_mv_test.go
  tfexec/state_rm_test.go
  tfexec/taint_test.go
  tfexec/terraform_test.go
  tfexec/untaint_test.go
  tfexec/upgrade012_test.go
  tfexec/upgrade013_test.go
  tfexec/version_test.go
  tfexec/workspace_delete_test.go
  tfexec/workspace_new_test.go
  tfexec/workspace_show_test.go
Labels: testing

#299 Test for runTerraformCmd leaked go-routine
  tfexec/cmd.go
  tfexec/cmd_default.go
  tfexec/cmd_default_test.go
  tfexec/cmd_linux.go
  tfexec/cmd_linux_test.go
  tfexec/internal/e2etest/errors_test.go
  tfexec/internal/e2etest/util_test.go
Labels: bug
